from __future__ import annotations

from pathlib import Path


def write_compiled_cli(root: Path, language: str) -> None:
    """Write a dependency-free CLI and build metadata for a toolchain evaluation."""
    if language == "rust":
        (root / "src").mkdir()
        (root / "Cargo.toml").write_text(
            '[package]\nname = "devlab-eval"\nversion = "0.1.0"\nedition = "2021"\n'
        )
        (root / "Cargo.lock").write_text(
            "# This file is automatically @generated by Cargo.\n"
            "# It is not intended for manual editing.\n"
            "version = 3\n\n"
            "[[package]]\n"
            'name = "devlab-eval"\n'
            'version = "0.1.0"\n'
        )
        (root / "src/main.rs").write_text(
            'fn main() {\n    println!("hello from rust");\n}\n'
        )
        (root / ".gitignore").write_text("/target/\n")
        return
    if language == "go":
        (root / "go.mod").write_text("module example.invalid/devlab-eval\n\ngo 1.22\n")
        (root / "main.go").write_text(
            'package main\n\nimport "fmt"\n\nfunc main() { fmt.Println("hello from go") }\n'
        )
        return
    if language not in {"c", "cpp"}:
        raise ValueError(f"unsupported compiled evaluation language: {language}")
    extension = "c" if language == "c" else "cpp"
    standard = "11" if language == "c" else "20"
    project_language = "C" if language == "c" else "CXX"
    message = "hello from c" if language == "c" else "hello from cpp"
    source = (
        '#include <stdio.h>\nint main(void) { puts("hello from c"); return 0; }\n'
        if language == "c"
        else '#include <iostream>\nint main() { std::cout << "hello from cpp\\n"; }\n'
    )
    (root / f"main.{extension}").write_text(source)
    (root / "CMakeLists.txt").write_text(
        "cmake_minimum_required(VERSION 3.20)\n"
        f"project(devlab_eval LANGUAGES {project_language})\n"
        f"set(CMAKE_{project_language}_STANDARD {standard})\n"
        f"add_executable(devlab-eval main.{extension})\n"
        "enable_testing()\n"
        "add_test(NAME output COMMAND devlab-eval)\n"
        f'set_tests_properties(output PROPERTIES PASS_REGULAR_EXPRESSION "{message}")\n'
    )
    (root / "CMakePresets.json").write_text(
        '{\n  "version": 3,\n  "configurePresets": [{\n'
        '    "name": "dev", "generator": "Unix Makefiles",\n'
        '    "binaryDir": "${sourceDir}/build"\n'
        '  }],\n  "buildPresets": [{"name": "dev", "configurePreset": "dev"}],\n'
        '  "testPresets": [{"name": "dev", "configurePreset": "dev"}]\n}\n'
    )
    (root / ".gitignore").write_text("/build/\n")


def write_mixed_rust_go_component(root: Path, language: str) -> None:
    component = root / f"{language}-component"
    component.mkdir()
    write_compiled_cli(component, language)


def write_mixed_rust_go_integration(root: Path) -> None:
    (root / "Makefile").write_text(
        ".PHONY: check\n"
        "check:\n"
        "\tcargo test --manifest-path rust-component/Cargo.toml\n"
        "\tcd go-component && go test ./...\n"
    )
    gitignore = root / ".gitignore"
    existing = gitignore.read_text() if gitignore.exists() else ""
    gitignore.write_text(existing + "/rust-component/target/\n")


def write_calculator(root: Path, *, include_subtract: bool) -> None:
    subtract_block = (
        "    if operation == 'subtract':\n"
        "        return left - right\n"
        if include_subtract
        else ""
    )
    root.joinpath("calculator.py").write_text(
        "from __future__ import annotations\n\n"
        "import argparse\n\n\n"
        "def calculate(operation: str, left: int, right: int) -> int:\n"
        "    if operation == 'add':\n"
        "        return left + right\n"
        f"{subtract_block}"
        "    raise ValueError(f'unsupported operation: {operation}')\n\n\n"
        "def main() -> None:\n"
        "    parser = argparse.ArgumentParser()\n"
        "    parser.add_argument('operation', choices=['add', 'subtract'])\n"
        "    parser.add_argument('left', type=int)\n"
        "    parser.add_argument('right', type=int)\n"
        "    args = parser.parse_args()\n"
        "    print(calculate(args.operation, args.left, args.right))\n\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def write_http_app(root: Path) -> None:
    root.joinpath("app.py").write_text(
        "from __future__ import annotations\n\n"
        "import argparse\n"
        "from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer\n"
        "from urllib.parse import parse_qs, urlparse\n\n\n"
        "class Handler(BaseHTTPRequestHandler):\n"
        "    def do_GET(self):\n"
        "        parsed = urlparse(self.path)\n"
        "        if parsed.path == '/health':\n"
        "            self._text(200, 'ok')\n"
        "            return\n"
        "        if parsed.path == '/echo':\n"
        "            value = parse_qs(parsed.query).get('value', [''])[0]\n"
        "            self._text(200, value)\n"
        "            return\n"
        "        self._text(404, 'not found')\n\n"
        "    def log_message(self, format, *args):\n"
        "        return\n\n"
        "    def _text(self, status, body):\n"
        "        data = body.encode()\n"
        "        self.send_response(status)\n"
        "        self.send_header('Content-Type', 'text/plain')\n"
        "        self.send_header('Content-Length', str(len(data)))\n"
        "        self.end_headers()\n"
        "        self.wfile.write(data)\n\n\n"
        "def main():\n"
        "    parser = argparse.ArgumentParser()\n"
        "    parser.add_argument('--port', type=int, required=True)\n"
        "    args = parser.parse_args()\n"
        "    server = ThreadingHTTPServer(('127.0.0.1', args.port), Handler)\n"
        "    server.serve_forever()\n\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def write_stateful_todo_api(root: Path) -> None:
    source_dir = root / "src/todo_api"
    tests_dir = root / "tests"
    source_dir.mkdir(parents=True)
    tests_dir.mkdir()
    (source_dir / "__init__.py").write_text("")
    (source_dir / "server.py").write_text(
        "from __future__ import annotations\n\n"
        "import argparse\n"
        "import json\n"
        "from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer\n"
        "from urllib.parse import urlparse\n\n\n"
        "class TodoStore:\n"
        "    def __init__(self):\n"
        "        self.items = []\n"
        "        self.next_id = 1\n\n"
        "    def create(self, title):\n"
        "        item = {'id': self.next_id, 'title': title, 'completed': False}\n"
        "        self.next_id += 1\n"
        "        self.items.append(item)\n"
        "        return item\n\n"
        "    def delete(self, item_id):\n"
        "        before = len(self.items)\n"
        "        self.items = [item for item in self.items if item['id'] != item_id]\n"
        "        return len(self.items) != before\n\n\n"
        "store = TodoStore()\n\n\n"
        "class Handler(BaseHTTPRequestHandler):\n"
        "    def do_GET(self):\n"
        "        path = urlparse(self.path).path\n"
        "        if path == '/health':\n"
        "            self._json(200, {'status': 'ok'})\n"
        "            return\n"
        "        if path == '/todos':\n"
        "            self._json(200, {'todos': store.items})\n"
        "            return\n"
        "        self._json(404, {'error': 'not found'})\n\n"
        "    def do_POST(self):\n"
        "        if urlparse(self.path).path != '/todos':\n"
        "            self._json(404, {'error': 'not found'})\n"
        "            return\n"
        "        try:\n"
        "            length = int(self.headers.get('Content-Length', '0'))\n"
        "            payload = json.loads(self.rfile.read(length).decode())\n"
        "        except (TypeError, ValueError, json.JSONDecodeError):\n"
        "            self._json(400, {'error': 'invalid json'})\n"
        "            return\n"
        "        title = payload.get('title')\n"
        "        if not isinstance(title, str) or not title.strip():\n"
        "            self._json(400, {'error': 'title is required'})\n"
        "            return\n"
        "        self._json(201, store.create(title.strip()))\n\n"
        "    def do_DELETE(self):\n"
        "        path = urlparse(self.path).path\n"
        "        prefix = '/todos/'\n"
        "        if not path.startswith(prefix):\n"
        "            self._json(404, {'error': 'not found'})\n"
        "            return\n"
        "        try:\n"
        "            item_id = int(path.removeprefix(prefix))\n"
        "        except ValueError:\n"
        "            self._json(400, {'error': 'invalid id'})\n"
        "            return\n"
        "        if not store.delete(item_id):\n"
        "            self._json(404, {'error': 'not found'})\n"
        "            return\n"
        "        self._json(200, {'deleted': item_id})\n\n"
        "    def log_message(self, format, *args):\n"
        "        return\n\n"
        "    def _json(self, status, payload):\n"
        "        data = json.dumps(payload).encode()\n"
        "        self.send_response(status)\n"
        "        self.send_header('Content-Type', 'application/json')\n"
        "        self.send_header('Content-Length', str(len(data)))\n"
        "        self.end_headers()\n"
        "        self.wfile.write(data)\n\n\n"
        "def main():\n"
        "    parser = argparse.ArgumentParser()\n"
        "    parser.add_argument('--port', type=int, required=True)\n"
        "    args = parser.parse_args()\n"
        "    server = ThreadingHTTPServer(('127.0.0.1', args.port), Handler)\n"
        "    server.serve_forever()\n\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )
    (tests_dir / "smoke_todo_api.py").write_text(
        "# Smoke behavior is verified by the DevLab evaluation harness.\n"
        "# Run the service with: python -m src.todo_api.server --port 8000\n"
    )
    (root / "Makefile").write_text(
        ".PHONY: run test\n"
        "PORT ?= 8000\n\n"
        "run:\n"
        "\tpython -m src.todo_api.server --port $(PORT)\n\n"
        "test:\n"
        "\tpython tests/smoke_todo_api.py\n"
    )
    (root / "README.md").write_text(
        "# Todo API\n\n"
        "Run with `make run PORT=8000`. Validate with `make test`.\n\n"
        "Endpoints: `GET /health`, `GET /todos`, `POST /todos`, "
        "and `DELETE /todos/{id}`. Data is in-memory only.\n"
    )
    (root / ".gitignore").write_text("__pycache__/\n*.pyc\n.pytest_cache/\n.venv/\n")


def write_static_frontend(root: Path) -> None:
    static_dir = root / "static"
    static_dir.mkdir()
    (static_dir / "index.html").write_text(
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <title>Todo App</title>\n"
        "  <link rel=\"stylesheet\" href=\"styles.css\">\n"
        "</head>\n"
        "<body>\n"
        "  <main>\n"
        "    <h1>Todo App</h1>\n"
        "    <form id=\"todo-form\">\n"
        "      <label for=\"todo-title\">Title</label>\n"
        "      <input id=\"todo-title\" name=\"title\" required>\n"
        "      <button type=\"submit\">Add todo</button>\n"
        "    </form>\n"
        "    <p id=\"error-message\" role=\"alert\"></p>\n"
        "    <ul id=\"todo-list\"></ul>\n"
        "  </main>\n"
        "  <script src=\"app.js\"></script>\n"
        "</body>\n"
        "</html>\n"
    )
    (static_dir / "app.js").write_text(
        "const form = document.querySelector('#todo-form');\n"
        "const input = document.querySelector('#todo-title');\n"
        "const list = document.querySelector('#todo-list');\n"
        "const errorMessage = document.querySelector('#error-message');\n\n"
        "function showError(message) { errorMessage.textContent = message || ''; }\n\n"
        "async function loadTodos() {\n"
        "  const response = await fetch('/todos');\n"
        "  const data = await response.json();\n"
        "  renderTodos(data.todos || []);\n"
        "}\n\n"
        "function renderTodos(todos) {\n"
        "  list.innerHTML = '';\n"
        "  for (const todo of todos) {\n"
        "    const item = document.createElement('li');\n"
        "    item.textContent = todo.title + ' ';\n"
        "    const button = document.createElement('button');\n"
        "    button.type = 'button';\n"
        "    button.textContent = 'Delete';\n"
        "    button.addEventListener('click', () => deleteTodo(todo.id));\n"
        "    item.appendChild(button);\n"
        "    list.appendChild(item);\n"
        "  }\n"
        "}\n\n"
        "async function addTodo(title) {\n"
        "  const response = await fetch('/todos', {\n"
        "    method: 'POST',\n"
        "    headers: {'Content-Type': 'application/json'},\n"
        "    body: JSON.stringify({title})\n"
        "  });\n"
        "  if (!response.ok) { showError('Todo title is required.'); return; }\n"
        "  input.value = '';\n"
        "  showError('');\n"
        "  await loadTodos();\n"
        "}\n\n"
        "async function deleteTodo(id) {\n"
        "  const response = await fetch(`/todos/${id}`, {method: 'DELETE'});\n"
        "  if (!response.ok) { showError('Could not delete todo.'); return; }\n"
        "  showError('');\n"
        "  await loadTodos();\n"
        "}\n\n"
        "form.addEventListener('submit', event => {\n"
        "  event.preventDefault();\n"
        "  addTodo(input.value);\n"
        "});\n\n"
        "loadTodos();\n"
    )
    (static_dir / "styles.css").write_text(
        "body { font-family: sans-serif; max-width: 42rem; margin: 2rem auto; }\n"
        "form { display: flex; gap: 0.5rem; }\n"
        "#error-message { color: #b00020; }\n"
    )
    readme = root / "README.md"
    readme.write_text(
        readme.read_text()
        + "\n\n"
        + "## Static frontend\n\n"
        + "The vanilla HTML/CSS/JS frontend is in `static/`. Open `static/index.html` "
        + "through a local static file server or serve it alongside the API so browser "
        + "requests to `/todos` reach the todo API. There is no frontend build step.\n"
    )


def write_compose_deployment_artifacts(root: Path) -> None:
    (root / "compose.yaml").write_text(
        "services:\n"
        "  todo-api:\n"
        "    build:\n"
        "      context: .\n"
        "      dockerfile: Containerfile\n"
        "    image: ${IMAGE:-todo-api:local}\n"
        "    ports:\n"
        "      - \"${PORT:-8000}:8000\"\n"
        "    environment:\n"
        "      TODO_ENV: local\n"
    )
    (root / ".env.example").write_text("IMAGE=todo-api:local\nPORT=8000\n")
    scripts_dir = root / "scripts"
    scripts_dir.mkdir(exist_ok=True)
    (scripts_dir / "smoke-test.sh").write_text(
        "#!/usr/bin/env sh\n"
        "set -eu\n"
        "BASE_URL=${BASE_URL:-http://127.0.0.1:${PORT:-8000}}\n"
        "python - <<'PY'\n"
        "import os, urllib.request\n"
        "base = os.environ.get('BASE_URL', 'http://127.0.0.1:8000')\n"
        "with urllib.request.urlopen(base + '/health', timeout=2) as response:\n"
        "    body = response.read().decode()\n"
        "assert 'ok' in body\n"
        "PY\n"
    )
    makefile = root / "Makefile"
    makefile.write_text(
        makefile.read_text()
        + "\n"
        + ".PHONY: compose-check deploy-local undeploy-local\n"
        + "COMPOSE ?= docker compose\n\n"
        + "compose-check:\n"
        + "\ttest -f compose.yaml\n"
        + "\ttest -f .env.example\n"
        + "\ttest -x scripts/smoke-test.sh || test -f scripts/smoke-test.sh\n\n"
        + "deploy-local:\n"
        + "\t$(COMPOSE) --env-file .env.example up --build -d\n\n"
        + "undeploy-local:\n"
        + "\t$(COMPOSE) --env-file .env.example down --remove-orphans\n"
    )
    readme = root / "README.md"
    readme.write_text(
        readme.read_text()
        + "\n\n"
        + "## Compose deployment\n\n"
        + "Copy `.env.example` to `.env` if local overrides are needed. Validate "
        + "Compose deployment artifacts with `make compose-check`. Start the local "
        + "Compose deployment with `make deploy-local`, smoke-test it with "
        + "`scripts/smoke-test.sh`, and tear it down with `make undeploy-local`. "
        + "Production deployment is out of scope.\n"
    )


def write_container_deployment_artifacts(root: Path) -> None:
    (root / "Containerfile").write_text(
        "FROM python:3.12-slim\n"
        "WORKDIR /app\n"
        "COPY src ./src\n"
        "EXPOSE 8000\n"
        "CMD [\"python\", \"-m\", \"src.todo_api.server\", \"--port\", \"8000\"]\n"
    )
    makefile = root / "Makefile"
    makefile.write_text(
        makefile.read_text()
        + "\n"
        + ".PHONY: image deployment-check\n"
        + "IMAGE ?= todo-api:local\n\n"
        + "image:\n"
        + "\tpodman build -t $(IMAGE) -f Containerfile .\n\n"
        + "deployment-check:\n"
        + "\ttest -f Containerfile\n"
        + "\tgrep -q 'src.todo_api.server' Containerfile\n"
    )
    readme = root / "README.md"
    readme.write_text(
        readme.read_text()
        + "\n\n"
        + "## Deployment\n\n"
        + "Build the local container image with `make image`. Verify deployment "
        + "artifacts with `make deployment-check`. The image runs the API on port 8000.\n"
    )
